### ISSUE TITLE
v1.3.2 does not work

### ISSUE THREAD

**Issue by sayem314** [dawsonbooth/react-native-use-dimensions#16]
v1.3.1 works fine!

![image](https://user-images.githubusercontent.com/14138401/86538858-630be400-bf1a-11ea-87be-3d7c6d67a975.png)

**Comment by dawsonbooth** [comment]
Looks like something was wrong with the build and it wasn't published with v1.3.2. Should be fixed in v1.3.3.

Thanks for saying something! Who knows how long the package would've gone without a working build lol...
